#
# This source file is part of the Stanford Spezi open source project
#
# SPDX-FileCopyrightText: 2025 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

dirs:
  - .
useGitIgnore: true
ignorePatterns:
  - pattern: '^doc:.*$'
  - pattern: '^http://localhost.*$'
  - pattern: '^https://swiftpackageindex\\.com/.*/documentation(/.*)?$'
replacementPatterns:
  - pattern: '(.*)#gh-dark-mode-only'
    replacement: '$1'
  - pattern: '(.*)#gh-light-mode-only'
    replacement: '$1'
